Niet (FGR is Duinen (F)) naar (Niet FGR is Duinen (T))
Spheer-ai/veg2hab pull request #56
Opened 2024-06-19 13:09 UTC by JRdeLange

Er is nu een uitzondering voor FGR, Bodem en LBK criteria in NietCriterium.str zodat die anders geprint worden.

2024-06-20 13:25 UTC, mark-boer commented
Is dit een vervolg op een andere PR? Meer changes dan ik had verwacht.

2024-06-20 13:27 UTC, JRdeLange commented
Ja, sorry, was ik even vergeten te vermelden. De laatste 2 commits zijn relevant, de eerdere 2 zijn van PR 55 SPH-678 FGR/Bodem/FBK typen in opm{i}

2024-06-20 13:36 UTC, mark-boer requested changes
Hmmm, wat misschien nog een een redelijke optie is:

```
def get_format(self, evaluation: MaybeBoolean):
    return f"FGR is {self.wanted_fgrtype.value}" + " ({MaybeBoolean})"

def __str__(self):
    return self.get_format(self._evaluation)
```

dan kun je vervolgens de __str__ overriden met:
```
def __str__(self):
    return "niet " + self.get_format(~self.evaluation)
```

2024-06-20 13:36 UTC, mark-boer commented on veg2hab/criteria.py
> +    def get_format_string(self):
Ik denk dat het netjes is als de __str__ hierboven ook gewoon zijn eigen get_format_string gebruikt. Dan heb je iets minder dubbelingen in je code staan.

2024-06-20 13:36 UTC, mark-boer commented on veg2hab/criteria.py
> +        if type(self.sub_criterium) in [FGRCriterium, BodemCriterium, LBKCriterium]:
`isinstance(self.sub_criterium, (FGRCriterium, BodemCriterium, LBKCriterium))`

Bovendien kan deze hele check toch weg, als we ervoor zorgen dat elk BeperkendCriterium een get_format_string functie heeft.

2024-07-16 13:51 UTC, JRdeLange commented
> Hmmm, wat misschien nog een een redelijke optie is:
> 
> ```
> def get_format(self, evaluation: MaybeBoolean):
>     return f"FGR is {self.wanted_fgrtype.value}" + " ({MaybeBoolean})"
> 
> def __str__(self):
>     return self.get_format(self._evaluation)
> ```
> 
> dan kun je vervolgens de **str** overriden met:
> 
> ```
> def __str__(self):
>     return "niet " + self.get_format(~self.evaluation)
> ```

Ik snap niet helemaal wat je bedoelt ben ik bang. Bedoel je in je tweede __str__ return "niet " + self.sub_criterium.get_format(~self.sub_criterium.evaluation)?

2024-07-25 08:11 UTC, mark-boer approved these changes

2024-07-25 08:12 UTC, merged