SPH-529 - Oude Bossenkaart mitsen
Spheer-ai/veg2hab pull request #73
Opened 2024-08-01 06:54 UTC by JRdeLange

2024-08-05 09:45 UTC, mark-boer requested changes
De daadwerkelijke check is nog niet geimplementeerd of wel? Ergens in main o.i.d.?

2024-08-05 09:45 UTC, mark-boer commented on veg2hab/bronnen.py
> +    def __init__(self, path: Path, mask: Optional[gpd.GeoDataFrame] = None):
`from_file` en evt. `from_github` toevoegen? Hoe groot is deze kaart, kunnen we 'm mee packagen?

2024-08-05 09:45 UTC, mark-boer commented on veg2hab/constants.py
> +OUDE_BOSSENKAART_PATH = resource_filename("veg2hab", "package_data/Oudebossen.gpkg")
Die vraag is beantwoord :-)

2024-08-05 13:14 UTC, mark-boer requested changes
Ook nog even toevoegen aan de README onder het kopje ` Bronbestanden die veg2hab gebruikt`

2024-08-07 09:42 UTC, JRdeLange commented
De oude bossenkaart wordt nu ook daadwerkelijk gebruikt, en dus ook gemaakt en doorgegeven in `run_3_definitietabel_en_mitsen()`.

Hij wordt benoemd in de readme, waar hij verwijst naar de versie in data/bronbestanden, net als dat de FGR doet.

Ik heb `for_habtype` toegevoegd aan de mits zodat deze werkt zoals beschreven was in `OMZETSTAPPEN.md` en hier de tests op aangepast.

2024-08-09 07:53 UTC, mark-boer approved these changes
top

2024-08-09 07:53 UTC, mark-boer commented on veg2hab/enums.py
> +    H9120: int = Field(ge=0, le=2)
ff een docstring hier, wat dit betekent zou fijn zijn!

2024-08-09 07:53 UTC, mark-boer commented on README.md
> + - [Oude Bossenkaart](./data/bronbestanden/Oudebossen.gpkg): dit bestand wordt gebruikt voor het controleren van beperkende criteria met betrekking tot bosgroeiplaatsen ouder dan 1850.
nice

2024-08-09 11:15 UTC, merged